# -*- coding: utf-8 -*-
"""dipoff-ts1 (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OalD7jtYyXbTaHGSevk6oLD4lBvjvTKF
"""

# Install PyTorch compiled with CUDA 11.8 for Kaggle compatibility
!pip uninstall -y torch torchvision torchaudio
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import os
import random
import torch
import numpy as np
import copy

seed = 12345

os.environ['PYTHONHASHSEED']=str(seed)
random.seed(seed)
torch.manual_seed(seed)
np.random.seed(seed)
torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import torch.nn as nn

class RNN_Model_Generic(nn.Module):
    def __init__(self, config, model_type):
        super(RNN_Model_Generic,self).__init__()
        # emb_size=256, hidden_size=128, hidden_layers=3, output=2

        self.model_type = model_type
        self.vocab_size = config["vocab_size"]
        self.emb_size = config["emb_size"]
        self.hidden_size = config["hidden_size"]
        self.lstm_layers = config["lstm_layers"]
        self.bi_lstm = config["bi_lstm"]
        self.reshape = config["reshape"]

        self.number_hidden_layers = config["number_hidder_layers"]
        self.dropout_prob = config["dropout_prob"]
        self.hidden_layers = []

        self.hidden_shape = self.hidden_size*2 if self.bi_lstm else self.hidden_size

        self.embedding = None
        if self.vocab_size > 0:
            self.embedding = nn.Embedding(self.vocab_size, self.emb_size, padding_idx=0)


        if model_type == "LSTM":
            self.lstm = nn.LSTM(self.emb_size, self.hidden_size, num_layers=self.lstm_layers,
                            batch_first=True, bidirectional=self.bi_lstm)
        elif model_type == "GRU":
            self.lstm= nn.GRU(self.emb_size, self.hidden_size, num_layers=self.lstm_layers,
                           batch_first=True, bidirectional=self.bi_lstm)
        else:
            self.lstm= nn.RNN(self.emb_size, self.hidden_size, num_layers=self.lstm_layers,
                           batch_first=True, bidirectional=self.bi_lstm)

        start_size = self.hidden_shape

        self.relu = nn.ReLU
        # self.dropout = nn.Dropout(self.dropout_prob)

        for i in range(self.number_hidden_layers):
            self.hidden_layers.append(nn.Sequential(
                nn.Linear(start_size, start_size // 2),
                nn.ReLU(),
                nn.Dropout(self.dropout_prob)))

            start_size = start_size // 2

        self.hidden_layers = nn.ModuleList(self.hidden_layers)
        self.output = nn.Linear(start_size,2)


    def forward(self,x):
        dir = 2 if self.bi_lstm else 1
        h = torch.zeros((self.lstm_layers*dir, x.size(0), self.hidden_size)).to(device)
        c = torch.zeros((self.lstm_layers*dir, x.size(0), self.hidden_size)).to(device)

        if self.embedding is not None:
            x = x.type(torch.LongTensor).to(device)
            x = self.embedding(x)
        elif self.reshape:
            x = x.view(x.shape[0],x.shape[1],1)

        if self.model_type == "LSTM":
            x, (hidden, cell) = self.lstm(x, (h,c))
        else:
            x, hidden = self.lstm(x, h)

        x = x[:, -1, :]

        # print(x.shape)
        for i, layer in enumerate(self.hidden_layers):
            x = layer(x)
            # print(x.shape)
        x = self.output(x)
        # print(x.shape)
        return x

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class TrainerDataset(Dataset):
    def __init__(self, inputs, targets):
        self.inputs= inputs
        self.targets = torch.from_numpy(targets)

    def __len__(self):
        return len(self.targets)

    def __getitem__(self, idx):
        return torch.Tensor(self.inputs[idx]), self.targets[idx]

def trainer(config, train_x, train_y, num_epochs=100, batch_size=32, debug=False, lr=0.0001, model_type="LSTM"):
    train_pos_idx = np.where(train_y==1)
    train_neg_idx = np.where(train_y==0)

    train_xp = train_x[train_pos_idx]
    train_xn = train_x[train_neg_idx]

    train_yp = train_y[train_pos_idx]
    train_yn = train_y[train_neg_idx]

    train_dataset_pos = TrainerDataset(train_xp, train_yp)
    train_dataloader_pos = DataLoader(train_dataset_pos, batch_size=batch_size//2, shuffle=True)
    train_dataset_neg = TrainerDataset(train_xn, train_yn)
    train_dataloader_neg = DataLoader(train_dataset_neg, batch_size=batch_size//2, shuffle=True)

    seed = 12345
    os.environ['PYTHONHASHSEED']=str(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    model = RNN_Model_Generic(config, model_type).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(),lr=lr)
    n_total_steps = len(train_dataloader_neg)
    model.train()

    history = {'train_loss': []}

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for i, (train_features_neg, train_labels_neg) in enumerate(train_dataloader_neg):
            train_features_pos, train_labels_pos = next(iter(train_dataloader_pos))
            train_features = torch.cat((train_features_pos, train_features_neg), 0)
            train_labels = torch.cat((train_labels_pos, train_labels_neg), 0)

            outputs = model(train_features.to(device))
            loss = criterion(outputs, train_labels.to(device))

            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

            if (i+1) % 200 == 0:
                print (f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{n_total_steps}], Loss: {loss.item():.4f}')
                if debug:
                    return model, history

        epoch_loss /= len(train_dataloader_neg)
        history['train_loss'].append(epoch_loss)

    return model, history

def tester(model, test_x, test_y):
    test_dataset = TrainerDataset(test_x, test_y)
    test_dataloader = DataLoader(test_dataset, batch_size=128, shuffle=False)
    model.eval()
    results = []
    true_labels = []
    with torch.no_grad():
        for test_features, test_labels in test_dataloader:
            outputs = model(test_features.to(device)).detach().to("cpu")
            results.extend(outputs)
            true_labels.extend(test_labels)
    return true_labels, results

class Stats:
    def __init__(self):
        self.acc = 0
        self.pre = 0
        self.re = 0
        self.f1 = 0
        self.roc = 0
        self.prc = 0
        self.tn = 0
        self.fp = 0
        self.fn = 0
        self.tp = 0
    def print(self):
        print('Accuracy: %.4f' %self.acc)
        print('Precision: %.4f' %self.pre)
        print('Recall: %.4f' %self.re)
        print('F1 Score: %.4f' %self.f1)
        print('ROC: %.4f' %self.roc)
        print('PR AUC: %.4f' %self.prc)
        print("Confusion Matrix")
        print(self.tn, "\t", self.fp)
        print(self.fn, "\t", self.tp)

from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, roc_curve, f1_score  # <-- Added roc_curve, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
from sklearn.metrics import accuracy_score
import numpy as np
import torch

def eval_matrices(model, test_x, test_y, debug = True):
    true_y, results = tester(model, test_x, test_y)

    # Fixed the UserWarning by explicitly adding dim=-1
    predictions = [torch.nn.functional.softmax(r, dim=-1) for r in results]
    pred_y = np.array([y[1].item() for y in predictions])
    pred_y_list = []
    test_y = np.array([y.item() for y in true_y])

    for x in pred_y:
        if(x>0.5):
            pred_y_list.append(1)
        else:
            pred_y_list.append(0)

    pred_y_list = np.array(pred_y_list)
    tn, fp, fn, tp = confusion_matrix(test_y, pred_y_list).ravel()

    # Generate data points for curves
    precision, recall, _ = precision_recall_curve(test_y, pred_y)
    fpr, tpr, _ = roc_curve(test_y, pred_y)  # <-- Added to get ROC data points

    auc_score = auc(recall, precision)
    acc = accuracy_score(test_y, pred_y_list)

    pr = -1
    re = -1
    f1 = -1
    try:
        pr = tp / (tp+fp)
        re = tp / (tp+fn)
        f1 = 2*pr*re / (pr+re)
    except:
        f1 = -1

    stats = Stats()
    stats.acc = acc
    stats.pre = pr
    stats.re = re
    stats.f1 = f1
    stats.roc = roc_auc_score(test_y, pred_y)
    stats.prc = auc_score
    stats.tn = tn
    stats.fp = fp
    stats.fn = fn
    stats.tp = tp

    if debug:
        print('Accuracy: %.4f' %acc)
        print('Precision: %.4f' %pr)
        print('Recall: %.4f' %re)
        print('F1 Score: %.4f' %f1)
        print('ROC:', roc_auc_score(test_y, pred_y))
        print('PR AUC: %.4f' % auc_score)

    # Package the curve data points for plotting and saving
    curve_data = {
        'fpr': fpr,
        'tpr': tpr,
        'recall': recall,
        'precision': precision,
        'pred_y': pred_y,
        'pred_y_list': pred_y_list,
        'test_y': test_y
    }

    return stats, curve_data  # <-- Modified to return both stats and curve points

def compute_metric_bootstraps(test_y, pred_y, pred_y_list, n_bootstraps=1000, alpha=0.05, seed=12345):
    """
    Computes both 95% Confidence Intervals and Mean +- Std for model metrics using bootstrapping.
    """
    bootstrapped_roc = []
    bootstrapped_f1 = []
    bootstrapped_pr_auc = []

    n_samples = len(test_y)
    rng = np.random.default_rng(seed=seed)

    print(f"Running {n_bootstraps} bootstrap iterations...")
    for i in range(n_bootstraps):
        # Resample indices with replacement
        boot_indices = rng.choice(n_samples, size=n_samples, replace=True)

        boot_y = test_y[boot_indices]
        boot_pred = pred_y[boot_indices]
        boot_pred_labels = pred_y_list[boot_indices]

        # Ensure bootstrap sample contains both classes to avoid ROC AUC errors
        if len(np.unique(boot_y)) < 2:
            continue

        # Calculate metrics for this bootstrap sample
        boot_roc = roc_auc_score(boot_y, boot_pred)
        boot_f1 = f1_score(boot_y, boot_pred_labels, zero_division=0)

        precision, recall, _ = precision_recall_curve(boot_y, boot_pred)
        boot_pr = auc(recall, precision)

        bootstrapped_roc.append(boot_roc)
        bootstrapped_f1.append(boot_f1)
        bootstrapped_pr_auc.append(boot_pr)

    # 1. Calculate Mean and Standard Deviation
    mean_roc, std_roc = np.mean(bootstrapped_roc), np.std(bootstrapped_roc)
    mean_f1, std_f1 = np.mean(bootstrapped_f1), np.std(bootstrapped_f1)
    mean_pr, std_pr = np.mean(bootstrapped_pr_auc), np.std(bootstrapped_pr_auc)

    # 2. Calculate Percentile Confidence Intervals (e.g., 2.5th and 97.5th)
    low_p = (alpha / 2.0) * 100
    high_p = (1.0 - alpha / 2.0) * 100

    ci_roc = (np.percentile(bootstrapped_roc, low_p), np.percentile(bootstrapped_roc, high_p))
    ci_f1 = (np.percentile(bootstrapped_f1, low_p), np.percentile(bootstrapped_f1, high_p))
    ci_pr = (np.percentile(bootstrapped_pr_auc, low_p), np.percentile(bootstrapped_pr_auc, high_p))

    print("\n--- Research Report: Model Performance Metrics (Bootstrap) ---")
    print(f"ROC AUC  : {mean_roc:.4f} ± {std_roc:.4f}  (95% CI: [{ci_roc[0]:.4f}, {ci_roc[1]:.4f}])")
    print(f"F1-Score : {mean_f1:.4f} ± {std_f1:.4f}  (95% CI: [{ci_f1[0]:.4f}, {ci_f1[1]:.4f}])")
    print(f"PR AUC   : {mean_pr:.4f} ± {std_pr:.4f}  (95% CI: [{ci_pr[0]:.4f}, {ci_pr[1]:.4f}])")

    return {
        'roc': {'mean': mean_roc, 'std': std_roc, 'ci': ci_roc},
        'f1': {'mean': mean_f1, 'std': std_f1, 'ci': ci_f1},
        'pr_auc': {'mean': mean_pr, 'std': std_pr, 'ci': ci_pr}
    }

def encoder(RNAseq, order=['A','T','C','G']):
    lookup_table = {order[0]:[1,0,0,0],
                    order[1]:[0,1,0,0],
                    order[2]:[0,0,1,0],
                    order[3]:[0,0,0,1]}
    encoded = np.zeros((len(RNAseq),len(order)))

    for i in range(len(RNAseq)):
        nu = RNAseq[i]
        if nu in lookup_table:
            encoded[i] = np.array(lookup_table[nu])
        else:
            print("Exception: Unindentified Nucleotide")

    return encoded
def superpose(encoded1, encoded2):
    if(len(encoded1) != len(encoded2)):
        print("Size Mismatch")
        return encoded1

    superposed = np.zeros(encoded1.shape)

    for i in range(len(encoded1)):
        for j in range(len(encoded1[i])):
            if encoded1[i][j] == encoded2[i][j]:
                superposed[i][j] = encoded1[i][j]
            else:
                superposed[i][j] = encoded1[i][j] + encoded2[i][j]
    return superposed

data_path = '/kaggle/input/datasets/anamulhoqueemtiaj/crispr/all_off_target.csv'
df = pd.read_csv(data_path)
enc_superposed = []
labels = []

for i in range(df.shape[0]):
    df_row = df.iloc[i]
    target = encoder(df_row['Target sgRNA'])
    off_target = encoder(df_row['Off Target sgRNA'])
    superposed = superpose(target, off_target)

    enc_superposed.append(superposed)
    labels.append(df_row['label'])

    if i%1000 == 0:
      print(i+1,"/",df.shape[0],"done")

print(len(enc_superposed))
print(len(labels))

from sklearn.model_selection import train_test_split
data_x = np.array(enc_superposed)
data_y = np.array(labels)

print(data_x.shape)
print(data_y.shape)


train_x, test_x, train_y, test_y = train_test_split(data_x, data_y,
                                                    stratify=data_y,
                                                    test_size=0.20,
                                                    random_state=5)
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)

best_config = {
    'vocab_size': 0,
    'emb_size': 4,
    'hidden_size': 512,
    'lstm_layers': 1,
    'bi_lstm': True,
    'number_hidder_layers': 2,
    'dropout_prob': 0.4,
    'reshape': False,
    'batch_size': 64,
    'epochs': 50,
    'learning_rate': 0.00010
}

config = best_config
debug = False
model_type = "LSTM"

model, history = trainer(config, train_x, train_y, num_epochs=config["epochs"], lr=config["learning_rate"], batch_size = config["batch_size"], model_type = model_type)
stats, curve_data = eval_matrices(model, test_x, test_y)
stats.print()

# Save the model weights
torch.save(model.state_dict(), 'dipoff_lstm_model.pth')
print("Model weights saved to 'dipoff_lstm_model.pth'")

import matplotlib.pyplot as plt
import numpy as np

# 1. Set up the plotting canvas (1 row, 3 columns)
plt.figure(figsize=(20, 5.5))

# --- Graph A: Learning Curve (Training Loss) ---
plt.subplot(1, 3, 1)
epochs = range(1, len(history['train_loss']) + 1)
plt.plot(epochs, history['train_loss'], marker='o', color='#1f77b4', linewidth=2, label='Train Loss')
plt.title('A. Training Loss Convergence', fontsize=13, fontweight='bold')
plt.xlabel('Epochs', fontsize=11)
plt.ylabel('Cross-Entropy Loss', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=10)

# --- Graph B: ROC AUC Curve (TPR vs FPR) ---
plt.subplot(1, 3, 2)
plt.plot(curve_data['fpr'], curve_data['tpr'], color='#ff7f0e', linewidth=2.5,
         label=f"Our Model (AUC = {stats.roc:.4f})")
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', linewidth=1.5, label='Random Guess (AUC = 0.5000)')
plt.title('B. Receiver Operating Characteristic (ROC)', fontsize=13, fontweight='bold')
plt.xlabel('False Positive Rate (FPR)', fontsize=11)
plt.ylabel('True Positive Rate (TPR)', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc="lower right", fontsize=10)

# --- Graph C: PR AUC Curve (Precision vs Recall) ---
plt.subplot(1, 3, 3)
plt.plot(curve_data['recall'], curve_data['precision'], color='#2ca02c', linewidth=2.5,
         label=f"Our Model (AUC = {stats.prc:.4f})")
plt.title('C. Precision-Recall Curve (PRC)', fontsize=13, fontweight='bold')
plt.xlabel('Recall', fontsize=11)
plt.ylabel('Precision', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc="lower left", fontsize=10)

# Render layout nicely
plt.tight_layout()
plt.show()

# 2. Save all numeric array data points for future use or external graphing tools
np.savez('crispr_model_curves.npz',
         epochs=np.array(list(epochs)),
         train_loss=np.array(history['train_loss']),
         fpr=curve_data['fpr'],
         tpr=curve_data['tpr'],
         recall=curve_data['recall'],
         precision=curve_data['precision'])

print("🎉 Success! Graphs generated and raw data coordinates saved as 'crispr_model_curves.npz'.")

# Run bootstrapping test
bootstrap_results = compute_metric_bootstraps(
    curve_data['test_y'],
    curve_data['pred_y'],
    curve_data['pred_y_list']
)