# -*- coding: utf-8 -*-
"""cclmoff-ts1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GaMhm8OT8fdWwvpnd5Km6br1NW1limYS
"""

import os
import random
import torch
import numpy as np
import pandas as pd
import copy

seed = 12345

os.environ['PYTHONHASHSEED']=str(seed)
random.seed(seed)
torch.manual_seed(seed)
np.random.seed(seed)
torch.cuda.manual_seed_all(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

import os
import sys

class Tee(object):
    def __init__(self, *files):
        self.files = files
    def write(self, obj):
        for f in self.files:
            f.write(obj)
            f.flush() # Ensure immediate writing
    def flush(self):
        for f in self.files:
            f.flush()

base_dir = "."
log_file_path = os.path.join(base_dir, "ts1_output.log")

# Keep the original log_file variable as existing code writes to it directly
log_file = open(log_file_path, "w", encoding="utf-8")

sys.stdout = Tee(sys.stdout, log_file)
sys.stderr = Tee(sys.stderr, log_file)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
print(f"Device: {device}\n")

print("Downloaded RNA-FM model\n")

"""# Model"""

!pip install rna-fm > /dev/null
!wget https://huggingface.co/cuhkaih/rnafm/resolve/b02d3594e4a25cd8b331c7319aa3746a8dfed2f0/RNA-FM_pretrained.pth > /dev/null

!mkdir -p ~/.cache/torch/hub/checkpoints
!mv RNA-FM_pretrained.pth ~/.cache/torch/hub/checkpoints/

print("Downloaded RNA-FM model\n")

import torch
import torch.nn as nn
import fm

class ProtRNA(nn.Module):
    def __init__(self):
        super().__init__()

        # Load pretrained RNA-FM
        self.rna_model, self.rna_alphabet = fm.pretrained.rna_fm_t12()

        # === ADD <sep> TOKEN ===
        self._add_sep_token()

        # MLP head
        self.dense1 = nn.Linear(640, 64)
        self.dense2 = nn.Linear(64, 1)

        self.dropout = nn.Dropout(0.2)
        self.act = nn.Sigmoid()
        self.elu = nn.ELU()

        # Init linear layers
        for m in self.children():
            if isinstance(m, nn.Linear):
                torch.nn.init.kaiming_uniform_(m.weight.data)

    def _add_sep_token(self):
        alphabet = self.rna_alphabet

        # Add token to alphabet
        sep_token = "<sep>"
        if sep_token not in alphabet.tok_to_idx:
            new_idx = len(alphabet.all_toks)
            alphabet.all_toks.append(sep_token)
            alphabet.tok_to_idx[sep_token] = new_idx
            # alphabet.idx_to_tok[new_idx] = sep_token

            # Resize embedding
            old_emb = self.rna_model.embed_tokens
            old_num, dim = old_emb.weight.shape

            new_emb = nn.Embedding(old_num + 1, dim)
            new_emb.weight.data[:old_num] = old_emb.weight.data

            # Initialize <sep> from <eos>
            eos_id = alphabet.tok_to_idx["<eos>"]
            new_emb.weight.data[new_idx] = old_emb.weight.data[eos_id]

            self.rna_model.embed_tokens = new_emb

    def get_alphabet(self):
        return self.rna_alphabet

    def forward(self, tokens):
        rna_results = self.rna_model(tokens, repr_layers=[12])
        seq_emb = rna_results["representations"][12]

        # CLS token representation
        seq_emb = seq_emb[:, 0, :]

        x = self.elu(self.dropout(self.dense1(seq_emb)))
        x = self.dense2(self.dropout(x))
        # out = self.act(x)

        return x

"""# Sampler & DataLoader"""

import random
from torch.utils.data import Sampler

class BalancedBatchSampler(Sampler):
    def __init__(self, dataset, batch_size=128):
        assert batch_size % 2 == 0, "Batch size must be even"

        self.dataset = dataset
        self.batch_size = batch_size
        self.half = batch_size // 2

        self.pos_idx = []
        self.neg_idx = []

        for i in range(len(dataset)):
            label = int(dataset.data.iloc[i]["label"])
            if label == 1:
                self.pos_idx.append(i)
            else:
                self.neg_idx.append(i)

        self.num_batches = len(dataset) // batch_size


    def __iter__(self):
        print(self.num_batches)

        for _ in range(self.num_batches):

            pos_batch = random.sample(
                self.pos_idx,
                min(self.half, len(self.pos_idx))
            )

            neg_batch = random.sample(
                self.neg_idx,
                min(self.half, len(self.neg_idx))
            )

            batch = pos_batch + neg_batch
            random.shuffle(batch)

            yield batch

    def __len__(self):
        return self.num_batches

from torch.utils.data import Dataset
import numpy as np
import torch

class TrainerDataset(Dataset):
    def __init__(self, data):
        self.data = data.copy().reset_index(drop=True)

        # convert DNA -> RNA
        self.data["On"] = (
            self.data["Target sgRNA"]
            .astype(str)
            .str.upper()
            .str.replace("T", "U", regex=False)
        )

        self.data["Off"] = (
            self.data["Off Target sgRNA"]
            .astype(str)
            .str.upper()
            .str.replace("T", "U", regex=False)
        )

        self.labels = self.data["label"].to_numpy()

        # class stats
        counts = self.data["label"].value_counts().sort_index()
        self.class_num_list = counts.tolist()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        row = self.data.iloc[idx]

        seq = f"{row['On']}<sep>{row['Off']}".replace("_", "-")
        label = int(row["label"])

        return {
            "seq": seq,
            "label": torch.tensor(label, dtype=torch.long)
        }

class TestDataset(Dataset):
    def __init__(self, data):
        self.data = data.copy().reset_index(drop=True)

        self.data["On"] = (
            self.data["Target sgRNA"]
            .astype(str)
            .str.upper()
            .str.replace("T", "U", regex=False)
        )

        self.data["Off"] = (
            self.data["Off Target sgRNA"]
            .astype(str)
            .str.upper()
            .str.replace("T", "U", regex=False)
        )

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]

        seq = f"{row['On']}<sep>{row['Off']}".replace("_", "-")
        label = int(row["label"])

        return {
            "seq": seq,
            "label": torch.tensor(label, dtype=torch.long)
        }

def collate_fn(batch, alphabet):
    sequences = [b["seq"] for b in batch]
    labels = torch.stack([b["label"] for b in batch])

    batch_converter = alphabet.get_batch_converter()
    _, _, tokens = batch_converter([(i, s) for i, s in enumerate(sequences)])

    return tokens, labels

import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, average_precision_score, f1_score
import time


class Trainer:
    def __init__(self, model, train_dataset, val_dataset=None, batch_size=128, device="cuda"):
        self.model = model.to(device)
        self.device = device
        self.alphabet = model.get_alphabet()
        self.batch_size = batch_size

        self.train_loader = DataLoader(
            train_dataset,
            batch_sampler=BalancedBatchSampler(train_dataset, batch_size),
            collate_fn=lambda b: collate_fn(b, self.alphabet)
        )

        self.val_loader = None
        if val_dataset is not None:
            self.val_loader = DataLoader(
                val_dataset,
                batch_size=batch_size,
                shuffle=False,
                collate_fn=lambda b: collate_fn(b, self.alphabet)
            )

        # Loss
        self.criterion = nn.BCEWithLogitsLoss()

        # Param groups (different LR)
        backbone_params = []
        head_params = []
        for name, p in model.named_parameters():
            if "rna_model" in name:
                backbone_params.append(p)
            else:
                head_params.append(p)

        self.optimizer = AdamW([
            {"params": backbone_params, "lr": 5e-4},
            {"params": head_params, "lr": 1e-3},
        ])

        # Store base LRs separately so warmup scaling doesn't compound
        self.base_lrs = [group["lr"] for group in self.optimizer.param_groups]

        self.epochs = 10
        self.warmup_epochs = 5
        self.history = {'train_loss': []} # Initialize history here

        # For best model saving
        self.best_val_pr_auc = -float('inf')

    def _set_lr(self, epoch):
        """Linear warmup for first 5 epochs (fixed: scales from base_lr, not cumulatively)"""
        scale = (epoch + 1) / self.warmup_epochs if epoch < self.warmup_epochs else 1.0
        for param_group, base_lr in zip(self.optimizer.param_groups, self.base_lrs):
            param_group["lr"] = base_lr * scale

    def train_one_epoch(self, epoch):
        self.model.train()
        total_loss = 0

        for step, (tokens, labels) in enumerate(self.train_loader):
            tokens = tokens.to(self.device)
            labels = labels.float().to(self.device).unsqueeze(1)

            preds = self.model(tokens)
            loss = self.criterion(preds, labels)

            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()

            total_loss += loss.item()

            if step % 100 == 0:
                print(f"Epoch {epoch} | Step {step} | Loss {loss.item():.4f}")

        avg_loss = total_loss / (step + 1)
        self.history['train_loss'].append(avg_loss) # Store the average loss
        return avg_loss

    @torch.no_grad()
    def evaluate(self):
        """Run inference on val_loader, return accuracy, PR-AUC, F1."""
        self.model.eval()
        all_labels = []
        all_probs = []

        for tokens, labels in self.val_loader:
            tokens = tokens.to(self.device)
            logits = self.model(tokens)
            probs = torch.sigmoid(logits).squeeze(1).cpu().numpy()

            all_probs.extend(probs.tolist())
            all_labels.extend(labels.numpy().tolist())

        preds_binary = [1 if p >= 0.5 else 0 for p in all_probs]

        acc = accuracy_score(all_labels, preds_binary)
        pr_auc = average_precision_score(all_labels, all_probs)
        f1 = f1_score(all_labels, preds_binary)

        return acc, pr_auc, f1

    def fit(self):
        start_time = time.time() # Start timer

        for epoch in range(self.epochs):

            self._set_lr(epoch)

            avg_loss = self.train_one_epoch(epoch)
            print(f"\nEpoch {epoch} completed | Avg Loss: {avg_loss:.4f}\n")

            if self.val_loader is not None:
                acc, pr_auc, f1 = self.evaluate()
                print(f"Epoch {epoch} | Val Accuracy: {acc:.4f} | Val PR-AUC: {pr_auc:.4f} | Val F1: {f1:.4f}\n")

                # Save best model based on PR-AUC
                if pr_auc > self.best_val_pr_auc:
                    self.best_val_pr_auc = pr_auc
                    torch.save(self.model.state_dict(), "best_protrna-ts1.pt")
                    print(f"New best model saved at epoch {epoch} with PR-AUC: {pr_auc:.4f}\n")

            else:
                print()

        # If no validation set is provided, save the latest model after all epochs
        if self.val_loader is None:
            torch.save(self.model.state_dict(), "latest_protrna.pt")
            print("No validation set provided, saving the latest model.\n")

        end_time = time.time() # End timer
        total_time = end_time - start_time
        print(f"Total training time: {total_time:.2f} seconds\n")

        return self.history

import torch
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    roc_curve,
    precision_recall_curve
)

class Stats:
    def __init__(self, acc, pre, re, f1, roc, prc):
        self.acc = acc
        self.pre = pre
        self.re = re
        self.f1 = f1
        self.roc = roc
        self.prc = prc


class Tester:
    def __init__(self, model, dataset, batch_size=128, device="cuda"):
        self.model = model.to(device)
        self.device = device

        self.alphabet = model.get_alphabet()

        self.loader = torch.utils.data.DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=False,
            collate_fn=lambda b: collate_fn(b, self.alphabet)
        )

    @torch.no_grad()
    def evaluate(self):
        self.model.eval()

        all_labels = []
        all_probs = []

        for tokens, labels in self.loader:
            tokens = tokens.to(self.device)

            preds = self.model(tokens).squeeze().cpu().numpy()

            all_probs.extend(preds.tolist())
            all_labels.extend(labels.numpy().tolist())

        y_true = np.array(all_labels)
        y_prob = np.array(all_probs)
        y_pred = (y_prob >= 0.5).astype(int)

        # Generate data points for curves
        precision, recall, _ = precision_recall_curve(y_true, y_prob)
        fpr, tpr, _ = roc_curve(y_true, y_prob)

        stats = Stats(
            acc=accuracy_score(y_true, y_pred),
            pre=precision_score(y_true, y_pred, zero_division=0),
            re=recall_score(y_true, y_pred, zero_division=0),
            f1=f1_score(y_true, y_pred, zero_division=0),
            roc=roc_auc_score(y_true, y_prob),
            prc=average_precision_score(y_true, y_prob)
        )

        curve_data = {
            'fpr': fpr,
            'tpr': tpr,
            'recall': recall,
            'precision': precision,
            'pred_y': y_prob,
            'pred_y_list': y_pred,
            'test_y': y_true
        }

        return stats, curve_data

from sklearn.model_selection import train_test_split

def load_and_split(file_path):
    # df = pd.read_csv(file_path, header=None, names=['Target sgRNA', 'Off Target sgRNA', 'label'])
    df = pd.read_csv(file_path)
    # df = df.sample(frac=0.01, random_state=42).reset_index(drop=True)
    df['label'] = df['label'].astype(int)
    Positive = df[df['label'] == 1]
    Negative = df[df['label'] == 0]
    Train_Negative, Test_Negative = train_test_split(Negative, test_size=0.2, random_state=42)
    Train_Positive, Test_Positive = train_test_split(Positive, test_size=0.2, random_state=42)
    train_data = pd.concat([Train_Negative, Train_Positive]).sample(frac=1, random_state=42).reset_index(drop=True)
    test_data = pd.concat([Test_Negative, Test_Positive]).sample(frac=1, random_state=42).reset_index(drop=True)
    return train_data, test_data

import os
def get_dataset_path(filename):
    paths = [
        os.path.join("", filename),
        os.path.join("datasets", filename),
        os.path.join("../datasets", filename),
        os.path.join("/kaggle/input/crispr", filename),
        os.path.join("/kaggle/input/datasets/anamulhoqueemtiaj/crispr", filename),
        filename
    ]
    for p in paths:
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f"Could not find {filename} in any standard location.")

file_path = "all_off_target.csv"
initial_train_data, test_data = load_and_split(file_path)

# Split 10% of the initial_train_data for validation
actual_train_data, val_data = train_test_split(initial_train_data, test_size=0.1, random_state=42)

# dataset
print(f"Training data shape: {actual_train_data.shape}")
print(f"Validation data shape: {val_data.shape}")

train_dataset = TrainerDataset(actual_train_data)
val_dataset = TestDataset(val_data)

model
model = ProtRNA()
trainer = Trainer(model, train_dataset, val_dataset=val_dataset, batch_size=128)

history = trainer.fit()

model = ProtRNA()
model.load_state_dict(torch.load("best_protrna-ts1.pt"))

test_dataset = TestDataset(test_data)
tester = Tester(model, test_dataset)
stats, curve_data = tester.evaluate()

print(stats.__dict__)
print(f"\n--- Research Report: Model Performance Metrics ---\n")
print(f"Accuracy: {stats.acc:.4f}\n")
print(f"Precision: {stats.pre:.4f}\n")
print(f"Recall: {stats.re:.4f}\n")
print(f"F1-Score: {stats.f1:.4f}\n")
print(f"ROC AUC: {stats.roc:.4f}\n")
print(f"PR AUC: {stats.prc:.4f}\n")

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(20, 5.5))

# --- Graph A: Learning Curve (Training Loss) ---
plt.subplot(1, 3, 1)
epochs = range(1, len(history['train_loss']) + 1)
plt.plot(epochs, history['train_loss'], marker='o', color='#1f77b4', linewidth=2, label='Train Loss')
plt.title('A. Training Loss Convergence', fontsize=13, fontweight='bold')
plt.xlabel('Epochs', fontsize=11)
plt.ylabel('Cross-Entropy Loss', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=10)

# --- Graph B: ROC AUC Curve (TPR vs FPR) ---
plt.subplot(1, 3, 2)
plt.plot(curve_data['fpr'], curve_data['tpr'], color='#ff7f0e', linewidth=2.5,
         label=f"Our Model (AUC = {stats.roc:.4f})")
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', linewidth=1.5, label='Random Guess (AUC = 0.5000)')
plt.title('B. Receiver Operating Characteristic (ROC)', fontsize=13, fontweight='bold')
plt.xlabel('False Positive Rate (FPR)', fontsize=11)
plt.ylabel('True Positive Rate (TPR)', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc="lower right", fontsize=10)

# --- Graph C: PR AUC Curve (Precision vs Recall) ---
plt.subplot(1, 3, 3)
plt.plot(curve_data['recall'], curve_data['precision'], color='#2ca02c', linewidth=2.5,
         label=f"Our Model (AUC = {stats.prc:.4f})")
plt.title('C. Precision-Recall Curve (PRC)', fontsize=13, fontweight='bold')
plt.xlabel('Recall', fontsize=11)
plt.ylabel('Precision', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc="lower left", fontsize=10)

# Render layout nicely
plt.tight_layout()
plt.show()

# 2. Save all numeric array data points for future use or external graphing tools
np.savez('cclmoff_model_curves.npz',
         epochs=np.array(list(epochs)),
         train_loss=np.array(history['train_loss']),
         fpr=curve_data['fpr'],
         tpr=curve_data['tpr'],
         recall=curve_data['recall'],
         precision=curve_data['precision'])

print("🎉 Success! Graphs generated and raw data coordinates saved as 'cclmoff_model_curves.npz'.")

import numpy as np
from sklearn.metrics import roc_auc_score, f1_score, auc, precision_recall_curve

def compute_metric_bootstraps(test_y, pred_y, pred_y_list, n_bootstraps=1000, alpha=0.05, seed=12345):
    """
    Computes both 95% Confidence Intervals and Mean +- Std for model metrics using bootstrapping.
    """
    bootstrapped_roc = []
    bootstrapped_f1 = []
    bootstrapped_pr_auc = []

    n_samples = len(test_y)
    rng = np.random.default_rng(seed=seed)

    print(f"Running {n_bootstraps} bootstrap iterations...\n")

    for i in range(n_bootstraps):
        # Resample indices with replacement
        boot_indices = rng.choice(n_samples, size=n_samples, replace=True)

        boot_y = test_y[boot_indices]
        boot_pred = pred_y[boot_indices]
        boot_pred_labels = pred_y_list[boot_indices]

        # Ensure bootstrap sample contains both classes to avoid ROC AUC errors
        if len(np.unique(boot_y)) < 2:
            continue

        # Calculate metrics for this bootstrap sample
        boot_roc = roc_auc_score(boot_y, boot_pred)
        boot_f1 = f1_score(boot_y, boot_pred_labels, zero_division=0)

        precision, recall, _ = precision_recall_curve(boot_y, boot_pred)
        boot_pr = auc(recall, precision)

        bootstrapped_roc.append(boot_roc)
        bootstrapped_f1.append(boot_f1)
        bootstrapped_pr_auc.append(boot_pr)

    # 1. Calculate Mean and Standard Deviation
    mean_roc, std_roc = np.mean(bootstrapped_roc), np.std(bootstrapped_roc)
    mean_f1, std_f1 = np.mean(bootstrapped_f1), np.std(bootstrapped_f1)
    mean_pr, std_pr = np.mean(bootstrapped_pr_auc), np.std(bootstrapped_pr_auc)

    # 2. Calculate Percentile Confidence Intervals (e.g., 2.5th and 97.5th)
    low_p = (alpha / 2.0) * 100
    high_p = (1.0 - alpha / 2.0) * 100

    ci_roc = (np.percentile(bootstrapped_roc, low_p), np.percentile(bootstrapped_roc, high_p))
    ci_f1 = (np.percentile(bootstrapped_f1, low_p), np.percentile(bootstrapped_f1, high_p))
    ci_pr = (np.percentile(bootstrapped_pr_auc, low_p), np.percentile(bootstrapped_pr_auc, high_p))

    print("\n--- Research Report: Model Performance Metrics ---\n")
    print(f"ROC AUC  : {mean_roc:.4f} \u00b1 {std_roc:.4f}  (95% CI: [{ci_roc[0]:.4f}, {ci_roc[1]:.4f}])\n")
    print(f"F1-Score : {mean_f1:.4f} \u00b1 {std_f1:.4f}  (95% CI: [{ci_f1[0]:.4f}, {ci_f1[1]:.4f}])\n")
    print(f"PR AUC   : {mean_pr:.4f} \u00b1 {std_pr:.4f}  (95% CI: [{ci_pr[0]:.4f}, {ci_pr[1]:.4f}])\n")

    return {
        'roc': {'mean': mean_roc, 'std': std_roc, 'ci': ci_roc},
        'f1': {'mean': mean_f1, 'std': std_f1, 'ci': ci_f1},
        'pr_auc': {'mean': mean_pr, 'std': std_pr, 'ci': ci_pr}
    }

# Run bootstrapping test
bootstrap_results = compute_metric_bootstraps(
    curve_data['test_y'],
    curve_data['pred_y'],
    curve_data['pred_y_list']
)

